services:
  mysql:
    image: mysql:8.0
    container_name: local-service-finder-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local_service_finder
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    image: local-service-finder-backend
    container_name: local-service-finder-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/local_service_finder
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"

volumes:
  mysql_data: