name: CI/CD Deploy Full Stack App to AWS EC2

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build Backend and Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Give permission to Maven wrapper
        run: chmod +x ./mvnw

      - name: Build Spring Boot backend
        run: ./mvnw clean package -DskipTests

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build React frontend
        working-directory: frontend
        run: npm run build

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2 using SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/Local-service-finder

            git fetch origin
            git reset --hard origin/main

            sudo docker compose up -d --build

            sudo docker compose ps
          EOF